<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class PublicUserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Obtener o crear el rol de usuario público
        $userRole = DB::table('roles')->where('name', 'user')->first();
        if (!$userRole) {
            $userRoleId = DB::table('roles')->insertGetId([
                'name' => 'user',
                'display_name' => 'Usuario Público',
                'description' => 'Usuario con acceso al sistema público de propiedades',
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        } else {
            $userRoleId = $userRole->id;
        }

        // Usuarios públicos harcodeados con usernames específicos
        $publicUsers = [
            [
                'id' => 20,
                'company_id' => 1,
                'name' => 'Alfa Forza',
                'email' => null,
                'username' => 'alfaforza',
                'password' => Hash::make('Alfa1Forza25!!'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 21,
                'company_id' => 1,
                'name' => 'Alfa Diamond',
                'email' => null,
                'username' => 'alfadiamond',
                'password' => Hash::make('AlfaDiamond225!!'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 22,
                'company_id' => 1,
                'name' => 'Alfa Pro',
                'email' => null,
                'username' => 'alfapro',
                'password' => Hash::make('A3lfaPro25!!'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 23,
                'company_id' => 1,
                'name' => 'Alfa Habitat',
                'email' => null,
                'username' => 'alfahabitat',
                'password' => Hash::make('AlfaHa4bitat25!!'),
                'gender' => 'female',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 24,
                'company_id' => 1,
                'name' => 'Alfa Elite',
                'email' => null,
                'username' => 'alfaelite',
                'password' => Hash::make('Alf5aElite25!!'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 25,
                'company_id' => 1,
                'name' => 'Alfa Futuro',
                'email' => null,
                'username' => 'alfafuturo',
                'password' => Hash::make('AlfaFuturo25!!6'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 26,
                'company_id' => 1,
                'name' => 'Alfa Grand Continental',
                'email' => null,
                'username' => 'alfagrandcontinental',
                'password' => Hash::make('Alfa7Continental25!!'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 27,
                'company_id' => 1,
                'name' => 'Alfa Lux',
                'email' => null,
                'username' => 'alfalux',
                'password' => Hash::make('AlfaLux258!!'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 28,
                'company_id' => 1,
                'name' => 'Alfa Premier',
                'email' => null,
                'username' => 'alfapremier',
                'password' => Hash::make('AlfaPre9mier25!!'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 29,
                'company_id' => 1,
                'name' => 'Alfa Link',
                'email' => null,
                'username' => 'alfalink',
                'password' => Hash::make('AlfaLink025!!'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 30,
                'company_id' => 1,
                'name' => 'Alfa Nys.sa',
                'email' => null,
                'username' => 'alfanyssa',
                'password' => Hash::make('AlfaNys1sa25!!'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 31,
                'company_id' => 1,
                'name' => 'Alfa Capital',
                'email' => null,
                'username' => 'alfacapital',
                'password' => Hash::make('A2lfaCapital25!!'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 32,
                'company_id' => 1,
                'name' => 'Alfa Max',
                'email' => null,
                'username' => 'alfamax',
                'password' => Hash::make('AlfaMa3x25!!'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 33,
                'company_id' => 1,
                'name' => 'Alfa Master',
                'email' => null,
                'username' => 'alfamaster',
                'password' => Hash::make('AlfaM4aster25!!'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 34,
                'company_id' => 1,
                'name' => 'Alfa Grand Central',
                'email' => null,
                'username' => 'alfagrandcentral',
                'password' => Hash::make('A5lfaGcentral25!!'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 35,
                'company_id' => 1,
                'name' => 'Alfa Grand Sky',
                'email' => null,
                'username' => 'alfagrandsky',
                'password' => Hash::make('Alfa6Gsky25!!'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 36,
                'company_id' => 1,
                'name' => 'Alfa Top',
                'email' => null,
                'username' => 'alfatop',
                'password' => Hash::make('A7lfaTop25!!'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 37,
                'company_id' => 1,
                'name' => 'Alfa Plus',
                'email' => null,
                'username' => 'alfaplus',
                'password' => Hash::make('AlfaPlu8s25!!'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 38,
                'company_id' => 1,
                'name' => 'Alfa Nova',
                'email' => null,
                'username' => 'alfanova',
                'password' => Hash::make('Alfa9Nova25!!'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 39,
                'company_id' => 1,
                'name' => 'Alfa Duo',
                'email' => null,
                'username' => 'alfaduo',
                'password' => Hash::make('AlfaDu0o25!!'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 40,
                'company_id' => 1,
                'name' => 'Alfa Prime',
                'email' => null,
                'username' => 'alfaprime',
                'password' => Hash::make('AlfaPrime125!!'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 41,
                'company_id' => 1,
                'name' => 'Alfa Residence',
                'email' => null,
                'username' => 'alfaresidence',
                'password' => Hash::make('AlfaResiden2ce25!!'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 42,
                'company_id' => 1,
                'name' => 'Alfa Golden',
                'email' => null,
                'username' => 'alfagolden',
                'password' => Hash::make('AlfaGold3en25!!'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 43,
                'company_id' => 1,
                'name' => 'Alfa Emporio',
                'email' => null,
                'username' => 'alfaemporio',
                'password' => Hash::make('A4lfaEmporio25!!'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 44,
                'company_id' => 1,
                'name' => 'Alfa Grand Horizonte',
                'email' => null,
                'username' => 'alfagrandhorizonte',
                'password' => Hash::make('AlfaGHorizont5e25!!'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 45,
                'company_id' => 1,
                'name' => 'Alfa Global',
                'email' => null,
                'username' => 'alfaglobal',
                'password' => Hash::make('Alfa6Global25!!'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 46,
                'company_id' => 1,
                'name' => 'Alfa VIP Inversiones',
                'email' => null,
                'username' => 'alfavipinversiones',
                'password' => Hash::make('AlfaVInversi7ones25!!'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 47,
                'company_id' => 1,
                'name' => 'Alfa Nexus',
                'email' => null,
                'username' => 'alfanexus',
                'password' => Hash::make('AlfaN8exus25!!'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 48,
                'company_id' => 1,
                'name' => 'Alfa Blue Avenue',
                'email' => null,
                'username' => 'alfablueavenue',
                'password' => Hash::make('Alfa9BlueAvenue25!!'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 49,
                'company_id' => 1,
                'name' => 'Alfa Smart',
                'email' => null,
                'username' => 'alfasmart',
                'password' => Hash::make('AlfaSmart025!!'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 50,
                'company_id' => 1,
                'name' => 'Alfa Home',
                'email' => null,
                'username' => 'alfahome',
                'password' => Hash::make('Al1faHome25!!'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 51,
                'company_id' => 1,
                'name' => 'Alfa New Life',
                'email' => null,
                'username' => 'alfanewlife',
                'password' => Hash::make('Alfa2Newlife25!!'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 52,
                'company_id' => 1,
                'name' => 'Alfa Titanium',
                'email' => null,
                'username' => 'alfatitanium',
                'password' => Hash::make('AlfaTita3nium25!!'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 53,
                'company_id' => 1,
                'name' => 'Alfa Red',
                'email' => null,
                'username' => 'alfared',
                'password' => Hash::make('Alfa4Red25!!'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 54,
                'company_id' => 1,
                'name' => 'Alfa Click',
                'email' => null,
                'username' => 'alfaclick',
                'password' => Hash::make('Alf6aClick25!!'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 55,
                'company_id' => 1,
                'name' => 'Alfa Ultra',
                'email' => null,
                'username' => 'alfaultra',
                'password' => Hash::make('Alfa1Ultra26!!'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 56,
                'company_id' => 1,
                'name' => 'Alfa City',
                'email' => null,
                'username' => 'alfacity',
                'password' => Hash::make('Alf2aCity26!!'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 57,
                'company_id' => 1,
                'name' => 'Alfa Proyecta',
                'email' => null,
                'username' => 'alfaproyecta',
                'password' => Hash::make('AlfaProyec3ta26!!'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 58,
                'company_id' => 1,
                'name' => 'Alfa Norte',
                'email' => 'null',
                'username' => 'alfanorte',
                'password' => Hash::make('Al5faNorte26!!'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 59,
                'company_id' => 1,
                'name' => 'Alfa Luxor',
                'email' => null,
                'username' => 'alfaluxor',
                'password' => Hash::make('AlfaLu6xor26!!'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 60,
                'company_id' => 1,
                'name' => 'Alfa Impacto',
                'email' => null,
                'username' => 'alfaimpacto',
                'password' => Hash::make('Alfa7impacto26!!'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            [
                'id' => 61,
                'company_id' => 1,
                'name' => 'Alfa Futuro 2',
                'email' => null,
                'username' => 'alfafuturo2',
                'password' => Hash::make('AlfaFuturo25!!6'),
                'gender' => 'male',
                'locale' => 'es',
                'status' => 'active',
                'login' => 'enable',
                'admin_approval' => 1,
                'permission_sync' => 1,
                'dark_theme' => 0,
                'rtl' => 0,
                'customised_permissions' => 0,
            ],
            ];

        // Insertar usuarios
        foreach ($publicUsers as $user) {
            $user['created_at'] = now();
            $user['updated_at'] = now();

            // Asegurar campos nulos existan en la tabla
            $user['two_factor_secret'] = null;
            $user['two_factor_recovery_codes'] = null;
            $user['two_factor_confirmed'] = 0;
            $user['two_factor_email_confirmed'] = 0;
            $user['image'] = null;
            $user['country_phonecode'] = null;
            $user['mobile'] = null;
            $user['salutation'] = null;
            $user['onesignal_player_id'] = null;
            $user['last_login'] = null;
            $user['email_notifications'] = 1;
            $user['country_id'] = null;
            $user['two_fa_verify_via'] = null;
            $user['two_factor_code'] = null;
            $user['two_factor_expires_at'] = null;
            $user['remember_token'] = null;
            $user['stripe_id'] = null;
            $user['pm_type'] = null;
            $user['pm_last_four'] = null;
            $user['trial_ends_at'] = null;
            $user['headers'] = null;
            $user['register_ip'] = null;
            $user['location_details'] = null;
            $user['inactive_date'] = null;
            $user['twitter_id'] = null;
            $user['is_client_contact'] = null;

            DB::table('users')->insert($user);

            // Asignar rol de usuario
            DB::table('role_user')->insert([
                'user_id' => $user['id'],
                'role_id' => $userRoleId,
            ]);
        }

        $this->command->info('✅ Usuarios públicos creados exitosamente:');
        $this->command->info('📧 alfaforza / Alfa1Forza25!!');
        $this->command->info('📧 alfadiamond / AlfaDiamond225!!');
        $this->command->info('📧 alfapro / A3lfaPro25!!');
        $this->command->info('📧 alfahabitat / AlfaHa4bitat25!!');
        $this->command->info('📧 alfaelite / Alf5aElite25!!');
        $this->command->info('📧 alfafuturo / AlfaFuturo25!!6');
        $this->command->info('📧 alfagrandcontinental / Alfa7Continental25!!');
        $this->command->info('📧 alfalux / AlfaLux258!!');
        $this->command->info('📧 alfapremier / AlfaPre9mier25!!');
        $this->command->info('📧 alfalink / AlfaLink025!!');
        $this->command->info('📧 alfanyssa / AlfaNys1sa25!!');
        $this->command->info('📧 alfacapital / A2lfaCapital25!!');
        $this->command->info('📧 alfax / AlfaMa3x25!!');
        $this->command->info('📧 alfamax / AlfaMa3x25!!');
        $this->command->info('📧 alfamaster / AlfaM4aster25!!');
        $this->command->info('📧 alfagrandcentral / A5lfaGcentral25!!');
        $this->command->info('📧 alfagrandsky / Alfa6Gsky25!!');
        $this->command->info('📧 alfatop / A7lfaTop25!!');
        $this->command->info('📧 alfaplus / AlfaPlu8s25!!');
        $this->command->info('📧 alfanova / Alfa9Nova25!!');
        $this->command->info('📧 alfaduo / AlfaDu0o25!!');
        $this->command->info('📧 alfaprime / AlfaPrime125!!');
        $this->command->info('📧 alfaresidence / AlfaResiden2ce25!!');
        $this->command->info('📧 alfagolden / AlfaGold3en25!!');
        $this->command->info('📧 alfaemporio / A4lfaEmporio25!!');
        $this->command->info('📧 alfagrandhorizonte / AlfaGHorizont5e25!!');
        $this->command->info('📧 alfaglobal / Alfa6Global25!!');
        $this->command->info('📧 alfavipinversiones / AlfaVInversi7ones25!!');
        $this->command->info('📧 alfablueavenue / Alfa9BlueAvenue25!!');
        $this->command->info('📧 alfasmart / AlfaSmart025!!');
        $this->command->info('📧 alfahome / Al1faHome25!!');
        $this->command->info('📧 alfanewlife / Alfa2Newlife25!!');
        $this->command->info('📧 alfatitanium / AlfaTita3nium25!!');
        $this->command->info('📧 alfared / Alfa4Red25!!');
        $this->command->info('📧 alfaclick / Alf6aClick25!!');
        $this->command->info('📧 alfaultra / Alfa1Ultra26!!');
        $this->command->info('📧 alfacity / Alf2aCity26!!');
        $this->command->info('📧 alfaproyecta / AlfaBusinessRe4lity26!!');
        $this->command->info('📧 alfanorte / Al5faNorte26!!');
        $this->command->info('📧 alfaluxor / AlfaLu6xor26!!');
        $this->command->info('📧 alfaimpacto / Alfa7impacto26!!');
        $this->command->info('🎯 Total: 40 usuarios creados');
    }
}