; Pool principal de PHP-FPM para producción
[www]

user  = www-data
group = www-data

; Escuchar en TCP para comunicarse con Nginx
listen = 0.0.0.0:9000

; ── Gestión de procesos (dynamic es seguro y flexible) ───────────────────────
pm                   = dynamic
pm.max_children      = 20
pm.start_servers     = 4
pm.min_spare_servers = 2
pm.max_spare_servers = 6
pm.max_requests      = 500

; ── Logs ─────────────────────────────────────────────────────────────────────
access.log          = /proc/self/fd/2
php_admin_value[error_log]  = /proc/self/fd/2
php_admin_flag[log_errors]  = on

; ── Variables de entorno ─────────────────────────────────────────────────────
clear_env = no
